### ISSUE TITLE
Playing the whole song thru = combo breaker?

### ISSUE THREAD

**Issue by derouinw** [derouinw/JSPong#35]
What I'm thinking is that we can have the song reset when you score/lose a point and there's a secondary goal to play it all the way through for a combo. Maybe it could count as a point as well. This would also encourage longer songs. What do you guys think?

**Comment by dragead** [comment]
I'm for it.

**Comment by derouinw** [comment]
Upgrading this to a goal. Let's do this.

**Comment by derouinw** [comment]
Done. Kinda subtle atm, but when bg music gets added, it should be more obvious. Maybe an additional sound too.
