### ISSUE TITLE
Should bounce notes only play one at a time?

### ISSUE THREAD

**Issue by derouinw** [derouinw/JSPong#36]
I'm just thinking that since when they play together, the "harmony" sound like crap. It would be pretty easy to implement.

**Comment by dragead** [comment]
I think yes. I also feel like notes shouldn't play on wall hits, only
paddle hits. Thoughts?

**Comment by derouinw** [comment]
I dunno, I think that having them play on walls makes sure that we have satisfactory saturation of sound. With only paddles, I think that with only paddles, the sounds will be too few and far between. But we can run that by our QA team (i.e. Dillon)

**Comment by dragead** [comment]
But there would also be background music, no? I don't think it would be a
big problem so long as we don't have dead silence.

**Comment by derouinw** [comment]
Yeah, that's true.

**Comment by derouinw** [comment]
Setting this to bug so I can fix it in the next update

**Comment by derouinw** [comment]
Whoops

**Comment by derouinw** [comment]
After some issues, finally got it to work.
